IN=tests/in/$(CTG)/test$(TEST).in
OUT=tests/out/$(CTG)/test$(TEST).out
AUX=tests/aux/$(CTG)/test$(TEST).aux

build:
	#complete if necessary

run_backtracking:
	python3 ./ExpTimeBKT/readGraf.py $(IN) > $(OUT)

run_reduction:
	python3 ./PolTimeRDC/readGraf.py $(IN) > $(AUX)

clean:
	#complete if necessary
